version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-cloud-bigquery
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.13.0
    - 2.13.1
    - 2.7.0
    - 2.8.0
    - 2.9.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: iso8601
    versions:
    - 0.1.13
  - dependency-name: jinja2
    versions:
    - 2.10.1
